server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contacts
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: JY@class4579

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true